"""Diff the live Next.js API against the committed static snapshot.

    python3 -m apix.store.api_parity [--base http://localhost:3000]

The 42 files in public/data/v1 were generated by the FastAPI reference
implementation over SQLite. If the TypeScript handlers over Neon return the
same bytes, the port is faithful -- endpoint shape, field names, rounding,
ordering and all. That is a stronger check than any unit test available in the
time, and it is why the snapshot is worth keeping.

Timestamps that MUST differ are ignored: served_at (now) and generated_at (the
vintage's own compute time, which is not the one the snapshot was built from).
"""
import argparse
import json
import pathlib
import sys
import urllib.error
import urllib.request

ROOT = pathlib.Path(__file__).resolve().parents[2].parent
SNAPSHOT = ROOT / "public" / "data" / "v1"

VOLATILE = {"served_at", "generated_at"}

# Lists whose ORDER is not part of the contract, compared as sets instead.
#
# cleaning.flags: the snapshot's order came from the screening pass iterating
# observations, and that sequence depends on how the store broke ties on
# collected_at. SQLite's sort is not stable, so the recorded order is
# arbitrary. The live API publishes a deterministic order (observation_id,
# flag); the flags themselves must still match exactly.
ORDER_INSENSITIVE = {".flags"}

# endpoint path -> snapshot file stem
TARGETS = [
    ("index", "index"),
    ("series", "series"),
    ("audit", "audit"),
    ("routes", "routes"),
    ("carriers", "carriers"),
    ("windows", "windows"),
    ("heatmap", "heatmap"),
    ("heatmap?metric=level", "heatmap__metric=level"),
    ("heatmap?metric=mean_fare", "heatmap__metric=mean_fare"),
    ("heatmap?metric=n_offers", "heatmap__metric=n_offers"),
    ("heatmap?metric=pct_change", "heatmap__metric=pct_change"),
    ("weights", "weights"),
    ("collection", "collection"),
    ("collection/runs?limit=60", "collection/runs__limit=60"),
    ("validation", "validation"),
    ("tariffs", "tariffs"),
    ("methodology", "methodology"),
    ("availability", "availability"),
    ("cleaning", "cleaning"),
    ("split", "split"),
]


def diff(a, b, path=""):
    out = []
    if isinstance(a, dict) and isinstance(b, dict):
        for k in sorted(set(a) | set(b)):
            if k in VOLATILE:
                continue
            if k not in a:
                out.append(f"{path}.{k}: EXTRA in live")
            elif k not in b:
                out.append(f"{path}.{k}: MISSING in live")
            else:
                out += diff(a[k], b[k], f"{path}.{k}")
    elif isinstance(a, list) and isinstance(b, list):
        if len(a) != len(b):
            out.append(f"{path}: length static={len(a)} live={len(b)}")
        if path in ORDER_INSENSITIVE:
            key = lambda o: json.dumps(o, sort_keys=True, default=str)   # noqa: E731
            sa, sb = sorted(map(key, a)), sorted(map(key, b))
            for x, y in zip(sa, sb):
                if x != y:
                    out.append(f"{path} (as a set): static={x} live={y}")
            return out
        for i, (x, y) in enumerate(zip(a, b)):
            out += diff(x, y, f"{path}[{i}]")
    elif a != b:
        out.append(f"{path}: static={a!r} live={b!r}")
    return out


def main() -> int:
    ap = argparse.ArgumentParser()
    ap.add_argument("--base", default="http://localhost:3000")
    ap.add_argument("--only", help="substring filter on the endpoint path")
    args = ap.parse_args()

    ok = missing = failed = 0
    for ep, stem in TARGETS:
        if args.only and args.only not in ep:
            continue
        f = SNAPSHOT / f"{stem}.json"
        if not f.exists():
            print(f"  {ep:<34} no snapshot file")
            continue
        try:
            with urllib.request.urlopen(f"{args.base}/api/v1/{ep}", timeout=60) as r:
                live = json.load(r)
        except urllib.error.HTTPError as e:
            body = e.read()[:200].decode("utf-8", "replace")
            print(f"  {ep:<34} HTTP {e.code}  {body}")
            missing += 1
            continue
        except Exception as e:                              # noqa: BLE001
            print(f"  {ep:<34} ERROR {e}")
            missing += 1
            continue

        d = diff(json.loads(f.read_text()), live)
        if not d:
            print(f"  {ep:<34} IDENTICAL")
            ok += 1
        else:
            print(f"  {ep:<34} {len(d)} difference(s)")
            for line in d[:6]:
                print(f"       {line}")
            if len(d) > 6:
                print(f"       ... and {len(d) - 6} more")
            failed += 1

    print(f"\n  identical {ok} | differing {failed} | unreachable {missing}")
    return 0 if failed == 0 and missing == 0 else 1


if __name__ == "__main__":
    sys.exit(main())
