-- Raw collection tables: the two tables the index engine actually reads.
--
-- Type mapping notes, because these are the places a careless port goes wrong:
--
--   REAL -> double precision, never numeric. SQLite REAL *is* IEEE-754
--   binary64, and double precision round-trips it bit-identically. numeric
--   would silently re-round every fare, and every published repro_hash is
--   taken over values derived from these columns.
--
--   INTEGER-as-boolean -> boolean. Loaded as (v <> 0).
--
--   TEXT timestamps -> timestamptz. The stored values are naive UTC
--   ('2026-09-10 00:25:55.586976'), so they are loaded AT TIME ZONE 'UTC'.
--
--   obs_date is generated from the UTC date, NOT Asia/Kolkata. apix/index/
--   model.py calls it the "IST calendar date" but apix/index/load.py computes
--   substr(collected_at,1,10) over a naive UTC value. The code is the contract
--   and every published hash is keyed on it; the docstring is simply wrong.

CREATE TABLE IF NOT EXISTS fare_observation (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,

    origin            text     NOT NULL,
    destination       text     NOT NULL,
    departure_date    date     NOT NULL,
    lead_time_days    smallint NOT NULL,
    carrier           text,
    flight_number     text,
    fare_class        text,

    total_fare        double precision NOT NULL,
    currency          text     NOT NULL DEFAULT 'INR',
    base_fare         double precision,
    taxes             double precision,
    udf               double precision,
    convenience_fee   double precision,
    fuel_charge_yq    double precision,

    availability      text,
    seats_left        integer,

    source            text     NOT NULL,
    source_url        text,
    collected_at      timestamptz NOT NULL,
    run_id            text,

    is_observed              boolean NOT NULL DEFAULT true,
    is_observed_fare_class   boolean NOT NULL DEFAULT false,
    is_observed_availability boolean NOT NULL DEFAULT false,

    notes             text,
    departure_time    text,      -- 'HH:MM' IST, as collected
    dep_band          text,      -- EM | MD | EV | NT
    is_nonstop        boolean,
    stops             smallint,

    obs_date date GENERATED ALWAYS AS (((collected_at AT TIME ZONE 'UTC')::date)) STORED,

    -- Mirrors the SQLite natural key exactly. NULLs are distinct in a unique
    -- index in both engines, so dedup behaviour is unchanged. Deliberately NOT
    -- using PG15 NULLS NOT DISTINCT, which would change which rows collapse.
    CONSTRAINT uq_fare_observation UNIQUE
      (origin, destination, departure_date, lead_time_days,
       carrier, flight_number, total_fare, source, collected_at)
);

CREATE INDEX IF NOT EXISTS ix_obs_route ON fare_observation (origin, destination);
CREATE INDEX IF NOT EXISTS ix_obs_dep   ON fare_observation (departure_date);
CREATE INDEX IF NOT EXISTS ix_obs_lead  ON fare_observation (lead_time_days);
CREATE INDEX IF NOT EXISTS ix_obs_coll  ON fare_observation (collected_at);
CREATE INDEX IF NOT EXISTS ix_obs_date  ON fare_observation (obs_date);
CREATE INDEX IF NOT EXISTS ix_obs_run   ON fare_observation (run_id);
CREATE INDEX IF NOT EXISTS ix_obs_band  ON fare_observation (dep_band);
-- /split only ever looks at rows where the source broke the fare out.
CREATE INDEX IF NOT EXISTS ix_obs_split ON fare_observation (carrier)
    WHERE base_fare IS NOT NULL AND taxes IS NOT NULL;


CREATE TABLE IF NOT EXISTS collection_run (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_id         text     NOT NULL,
    origin         text     NOT NULL,
    destination    text     NOT NULL,
    lead_time_days smallint NOT NULL,
    departure_date date     NOT NULL,
    source         text     NOT NULL,
    status         text     NOT NULL,   -- OK | NO_DATA | BLOCKED | ERROR
    n_quotes       integer  NOT NULL DEFAULT 0,
    elapsed_ms     integer,
    error          text,
    started_at     timestamptz NOT NULL,

    start_date date GENERATED ALWAYS AS (((started_at AT TIME ZONE 'UTC')::date)) STORED,

    -- SQLite has no unique key here, so a re-run duplicates rows. Adding one
    -- makes the collector's writes idempotent.
    CONSTRAINT uq_collection_run UNIQUE
      (run_id, origin, destination, lead_time_days, departure_date, source, started_at)
);

CREATE INDEX IF NOT EXISTS ix_run_runid ON collection_run (run_id);
CREATE INDEX IF NOT EXISTS ix_run_start ON collection_run (started_at DESC);
CREATE INDEX IF NOT EXISTS ix_run_day   ON collection_run (start_date);
