-- The computed vintage.
--
-- Follows the design in apix/migrations/004_index_tables.sql: the cell LINK is
-- the immutable fact and the level is derived from it, so re-referencing
-- produces a new vintage rather than revising history. Additions over 004:
-- a repro_hash on every point, real dimension columns on `weight` so handlers
-- can filter in SQL instead of parsing an opaque key, and the elementary
-- table carries the live weight in force that day.
--
-- Exactly one PUBLISHED run exists at a time (see ix_one_published), so every
-- read is "the current vintage" with no ordering ambiguity and no race.

CREATE TABLE IF NOT EXISTS weight_set (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    name                   text NOT NULL UNIQUE,
    price_reference_window date[],
    provenance             jsonb NOT NULL,       -- weights.build()[1], verbatim
    created_at             timestamptz NOT NULL DEFAULT now()
);

CREATE TABLE IF NOT EXISTS weight (
    weight_set_id  bigint   NOT NULL REFERENCES weight_set(id) ON DELETE CASCADE,
    level          text     NOT NULL CHECK (level IN ('ROUTE', 'LEAD', 'CELL')),
    origin         text     NOT NULL DEFAULT '',
    destination    text     NOT NULL DEFAULT '',
    lead_time_days smallint NOT NULL DEFAULT -1,
    carrier        text     NOT NULL DEFAULT '',
    dep_band       text     NOT NULL DEFAULT '',
    weight         double precision NOT NULL CHECK (weight >= 0),
    -- Postgres will not take expressions in a PRIMARY KEY, so the sentinel
    -- defaults above ('' / -1) stand in for the NULL dimensions instead.
    PRIMARY KEY (weight_set_id, level, origin, destination,
                 lead_time_days, carrier, dep_band)
);
CREATE INDEX IF NOT EXISTS ix_weight_route
    ON weight (weight_set_id, origin, destination) WHERE level = 'CELL';
CREATE INDEX IF NOT EXISTS ix_weight_carrier
    ON weight (weight_set_id, carrier) WHERE level = 'CELL';
CREATE INDEX IF NOT EXISTS ix_weight_lead
    ON weight (weight_set_id, lead_time_days) WHERE level = 'CELL';


CREATE TABLE IF NOT EXISTS index_run (
    id                bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    run_uid           text        NOT NULL UNIQUE,
    computed_at       timestamptz NOT NULL DEFAULT now(),
    generated_at_raw  text        NOT NULL,   -- cli.compute()'s own string, verbatim
    method_version    text,
    git_sha           text,
    weight_set_id     bigint      NOT NULL REFERENCES weight_set(id),
    config            jsonb       NOT NULL,   -- IndexConfig, for provenance only
    reference_factor  double precision NOT NULL,
    reference_label   text        NOT NULL,
    reference_window  date[]      NOT NULL,
    is_provisional    boolean     NOT NULL,
    status            text        NOT NULL
                      CHECK (status IN ('DRAFT', 'PUBLISHED', 'SUPERSEDED')),
    n_obs_in          integer,
    n_obs_selected    integer,
    n_collection_days integer     NOT NULL
);
CREATE UNIQUE INDEX IF NOT EXISTS ix_one_published
    ON index_run (status) WHERE status = 'PUBLISHED';


CREATE TABLE IF NOT EXISTS series (
    index_run_id   bigint NOT NULL REFERENCES index_run(id) ON DELETE CASCADE,
    series_id      text   NOT NULL,
    kind           text   NOT NULL
                   CHECK (kind IN ('headline', 'route', 'carrier', 'window', 'naive')),
    label          text,
    origin         text,
    destination    text,
    carrier        text,
    lead_time_days smallint,
    weight_share   double precision,
    n_cells        integer,
    PRIMARY KEY (index_run_id, series_id)
);


CREATE TABLE IF NOT EXISTS index_point (
    index_run_id     bigint  NOT NULL REFERENCES index_run(id) ON DELETE CASCADE,
    series_id        text    NOT NULL,
    freq             char(1) NOT NULL CHECK (freq IN ('D', 'W', 'M')),
    period_start     date    NOT NULL,
    period_end       date    NOT NULL,
    level            double precision NOT NULL CHECK (level > 0),
    link             double precision,
    weight_share     double precision,
    n_cells          integer,
    n_cells_imputed  integer,
    n_cells_thin     integer,
    n_cells_dead     integer,
    n_items_matched  integer,
    n_items_prev     integer,
    n_items_screened integer,
    weight_covered   double precision,
    weight_imputed   double precision,
    n_days           integer,
    is_provisional   boolean NOT NULL DEFAULT false,
    quality          text[]  NOT NULL DEFAULT '{}',
    method_version   text    NOT NULL,
    repro_hash       text    NOT NULL,
    PRIMARY KEY (index_run_id, series_id, freq, period_start),
    FOREIGN KEY (index_run_id, series_id)
        REFERENCES series (index_run_id, series_id) ON DELETE CASCADE
);
CREATE INDEX IF NOT EXISTS ix_point_series
    ON index_point (index_run_id, series_id, period_start);
CREATE INDEX IF NOT EXISTS ix_point_date
    ON index_point (index_run_id, period_start);


-- The reproducibility substrate. link + weight here are precisely the two maps
-- repro.canonical_payload hashes, so a third party can pull one date's rows and
-- recompute that day's index_point.repro_hash for themselves.
CREATE TABLE IF NOT EXISTS elementary_index (
    index_run_id       bigint   NOT NULL REFERENCES index_run(id) ON DELETE CASCADE,
    obs_date           date     NOT NULL,
    origin             text     NOT NULL,
    destination        text     NOT NULL,
    lead_time_days     smallint NOT NULL,
    carrier            text     NOT NULL,
    dep_band           text     NOT NULL,
    link               double precision,
    level              double precision,
    weight             double precision,   -- the LIVE weight in force that day
    n_matched          integer,
    n_prev             integer,
    n_cur              integer,
    n_screened         integer,
    is_imputed         boolean  NOT NULL DEFAULT false,
    imputation_source  text,                -- ROUTE_LEAD | ROUTE | ALL
    imputation_run_len integer,
    quality            text,                -- OK | THIN | IMPUTED | DEAD
    PRIMARY KEY (index_run_id, obs_date, origin, destination,
                 lead_time_days, carrier, dep_band)
);
CREATE INDEX IF NOT EXISTS ix_elem_date
    ON elementary_index (index_run_id, obs_date);
CREATE INDEX IF NOT EXISTS ix_elem_route
    ON elementary_index (index_run_id, origin, destination);
CREATE INDEX IF NOT EXISTS ix_elem_carrier
    ON elementary_index (index_run_id, carrier);


-- Which raw rows the engine actually selected. The 8 standing filters plus the
-- per-(date,route,lead) latest-genuine-sweep rule pick ~16k of 23k rows, and no
-- single WHERE clause expresses that -- so it is materialised.
CREATE TABLE IF NOT EXISTS index_observation (
    index_run_id   bigint NOT NULL REFERENCES index_run(id) ON DELETE CASCADE,
    observation_id bigint NOT NULL REFERENCES fare_observation(id),
    PRIMARY KEY (index_run_id, observation_id)
);

CREATE OR REPLACE VIEW v_selected_observation AS
SELECT io.index_run_id, o.*
  FROM index_observation io
  JOIN fare_observation o ON o.id = io.observation_id;


CREATE TABLE IF NOT EXISTS observation_flag (
    index_run_id   bigint NOT NULL REFERENCES index_run(id) ON DELETE CASCADE,
    observation_id bigint NOT NULL REFERENCES fare_observation(id),
    flag           text   NOT NULL,      -- EXTREME_MOVE | MAD_OUTLIER
    detail         text,
    PRIMARY KEY (index_run_id, observation_id, flag)
);


CREATE TABLE IF NOT EXISTS collection_day_stat (
    index_run_id bigint  NOT NULL REFERENCES index_run(id) ON DELETE CASCADE,
    obs_date     date    NOT NULL,
    n_cells      integer NOT NULL,
    run_ids      text[]  NOT NULL,
    first_ist    text,
    last_ist     text,
    PRIMARY KEY (index_run_id, obs_date)
);


CREATE TABLE IF NOT EXISTS sweep_exclusion (
    index_run_id bigint NOT NULL REFERENCES index_run(id) ON DELETE CASCADE,
    run_id       text   NOT NULL,
    reason       text   NOT NULL,
    PRIMARY KEY (index_run_id, run_id)
);
