-- Reference data that api/services/reference.py reads off disk today.
--
-- It moves into Postgres because a Vercel function should not be shipping a
-- 142 KB JSON file to answer /tariffs when there is a database right there,
-- and because "which states contribute the airfare weight" is a query, not a
-- file read.

-- MoSPI e-Sankhyiki, CPI 2024 item 07.3.3.1.2.01 (Airfare, item 294).
-- From apix/exports/mospi_airfare_index.csv.
CREATE TABLE IF NOT EXISTS mospi_point (
    period          char(7) PRIMARY KEY,     -- 'YYYY-MM'
    year            smallint NOT NULL,
    month           smallint NOT NULL,
    index_2024_base double precision NOT NULL
);

-- MoSPI Annexure 5.3d, 58 state x sector rows. From data/cpi2024_airfare_weights.csv.
CREATE TABLE IF NOT EXISTS cpi_weight_row (
    id                     bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    state_name             text NOT NULL,
    sector                 text NOT NULL,
    share_in_all_india_pct double precision NOT NULL,
    UNIQUE (state_name, sector)
);

-- Rule-135 published tariff sheets. One row per (airline, market, bound);
-- `levels` is the published fare ladder, kept as an ordered array because it
-- is read whole and never filtered.
CREATE TABLE IF NOT EXISTS tariff_row (
    id             bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    airline        text NOT NULL,
    city_a         text NOT NULL,
    city_b         text NOT NULL,
    bound          text NOT NULL CHECK (bound IN ('min', 'max')),
    origin         text,
    destination    text,
    stops          integer,
    fuel_charge_yq double precision,
    n_levels       integer,
    lowest_level   double precision,
    highest_level  double precision,
    levels         double precision[],
    source_url     text,
    UNIQUE (airline, city_a, city_b, bound)
);
CREATE INDEX IF NOT EXISTS ix_tariff_market ON tariff_row (airline, city_a, city_b);

CREATE TABLE IF NOT EXISTS tariff_source (
    airline   text PRIMARY KEY,
    url       text,
    found_via text
);

-- Single-row provenance for the tariff snapshot (retrieved date, note).
CREATE TABLE IF NOT EXISTS tariff_meta (
    k text PRIMARY KEY,
    v text
);
