/**
 * SIH26056 — Persistent data-mode indicator.
 *
 * Ported from the Airfare-CPI reference (rival SIH26056 submission, MIT
 * licensed) — read directly from its source, not reused as a file. Not yet
 * wired into any page; DATA_MODE / resolveDataMode / isRealData are kept
 * self-contained here rather than merged into src/api.js until this is
 * actually adopted.
 *
 * Renders one of several labels, always, in a full-width bar directly
 * beneath the header:
 *
 *   LIVE / SCRAPED DATA        collected from a real permitted source
 *   API-COLLECTED DATA         collected via authorized API integration
 *   SIMULATED DATA             generated by a calibrated simulator
 *   OFFLINE PREVIEW            replayed from a checked-in fixture
 *   SOURCE UNAVAILABLE         no data exists for this figure
 *   BACKEND UNREACHABLE        the backend could not be reached at all
 *
 * Deliberately NOT a tooltip, a badge in a corner, or a colour hint alone.
 * The reference repo's own audit found that synthetic figures had once been
 * shown under a "LIVE INDEX STREAM" label — so the distinction has to be
 * unavoidable, not discoverable. The banner stays visible even in LIVE mode,
 * because a reader should be able to confirm the mode, not infer it from the
 * absence of a warning.
 */

import { AlertTriangle, CheckCircle2, FlaskConical, WifiOff } from 'lucide-react';

/** Display modes. These strings are what the banner renders, verbatim. */
export const DATA_MODE = {
  LIVE: 'SCRAPED DATA',
  PORTAL_SCRAPED: 'SCRAPED DATA',
  API_COLLECTED: 'API-COLLECTED DATA',
  SIMULATED: 'SIMULATED DATA',
  OFFLINE: 'OFFLINE PREVIEW',
  UNAVAILABLE: 'SOURCE UNAVAILABLE',
  DISCONNECTED: 'BACKEND UNREACHABLE',
};

/** Map a backend `data_provenance` block onto a display mode. */
export function resolveDataMode(provenance) {
  if (!provenance) return DATA_MODE.UNAVAILABLE;
  if (provenance.display_label) {
    const label = provenance.display_label;
    if (label === 'SCRAPED DATA' || label === 'PORTAL-SCRAPED DATA') return DATA_MODE.PORTAL_SCRAPED;
    if (label === 'API-COLLECTED DATA') return DATA_MODE.API_COLLECTED;
    if (label === 'LIVE DATA') return DATA_MODE.LIVE;
    if (label === 'SIMULATED DATA') return DATA_MODE.SIMULATED;
    if (label === 'OFFLINE PREVIEW') return DATA_MODE.OFFLINE;
    if (label === 'SOURCE UNAVAILABLE') return DATA_MODE.UNAVAILABLE;
  }
  const method = String(provenance?.acquisition_method || '').toLowerCase();
  if (method === 'web_scrape') return DATA_MODE.PORTAL_SCRAPED;
  if (method === 'api') return DATA_MODE.API_COLLECTED;
  const sourceType = provenance?.source_type;
  if (sourceType === 'live') return DATA_MODE.LIVE;
  if (sourceType === 'simulated') return DATA_MODE.SIMULATED;
  if (sourceType === 'offline') return DATA_MODE.OFFLINE;
  return DATA_MODE.UNAVAILABLE;
}

/** True only for genuinely collected observations. */
export function isRealData(mode) {
  return mode === DATA_MODE.LIVE || mode === DATA_MODE.PORTAL_SCRAPED || mode === DATA_MODE.API_COLLECTED;
}

const PRESENTATION = {
  [DATA_MODE.LIVE]: {
    tone: 'live',
    Icon: CheckCircle2,
    detail:
      'Figures are computed by the index engine from airfare offers scraped across monitored airline portals and route quotations.',
  },
  [DATA_MODE.API_COLLECTED]: {
    tone: 'live',
    Icon: CheckCircle2,
    detail: 'Figures are computed from airfare offers retrieved via authorized API integration.',
  },
  [DATA_MODE.SIMULATED]: {
    tone: 'simulated',
    Icon: FlaskConical,
    detail:
      'Figures are generated research data used to exercise the collection and index pipeline. They are not observed market prices.',
  },
  [DATA_MODE.OFFLINE]: {
    tone: 'offline',
    Icon: FlaskConical,
    detail:
      'Figures are computed from a checked-in fixture replayed for offline demonstration. No source was contacted and these are not measurements.',
  },
  [DATA_MODE.UNAVAILABLE]: {
    tone: 'unavailable',
    Icon: AlertTriangle,
    detail: 'No index has been computed, so no figures are shown. Placeholder values are deliberately not substituted.',
  },
  [DATA_MODE.DISCONNECTED]: {
    tone: 'unavailable',
    Icon: WifiOff,
    detail: 'The backend is unreachable, so no figures are available. Values render as N/A rather than falling back to illustrative constants.',
  },
};

export default function DataModeBanner({ mode, reason, isPublishable, suppressionReason }) {
  const label = mode || DATA_MODE.DISCONNECTED;
  const presentation = PRESENTATION[label] || PRESENTATION[DATA_MODE.DISCONNECTED];
  const { tone, Icon, detail } = presentation;

  return (
    <div
      className={`data-mode-banner data-mode-${tone}`}
      role="status"
      aria-live="polite"
      data-testid="data-mode-banner"
      data-mode={label}
    >
      <div className="data-mode-inner">
        <span className="data-mode-label" data-testid="data-mode-label">
          <Icon size={15} aria-hidden="true" />
          {label}
        </span>
        <span className="data-mode-detail">{reason ? `${detail} ${reason}` : detail}</span>
      </div>

      {isPublishable === false && (
        <div className="data-mode-suppression" data-testid="data-mode-suppression">
          <AlertTriangle size={14} aria-hidden="true" />
          <span>
            <strong>Figure marked not publishable.</strong>{' '}
            {suppressionReason || 'Basket coverage is below the minimum required to publish a national figure.'}
          </span>
        </div>
      )}
    </div>
  );
}

/**
 * Compact inline variant, for use inside a panel that displays figures away
 * from the top-level banner. Same vocabulary, so a reader never has to
 * reconcile two labels.
 */
export function DataModeChip({ mode, className = '' }) {
  const label = mode || DATA_MODE.DISCONNECTED;
  const { tone } = PRESENTATION[label] || PRESENTATION[DATA_MODE.DISCONNECTED];
  return (
    <span
      className={`data-mode-chip data-mode-chip-${tone} ${className}`.trim()}
      data-testid="data-mode-chip"
      data-mode={label}
    >
      {label}
    </span>
  );
}
